---
name: 'pipeline-components-awesome-lint'
description: 'awesome-lint by pipeline components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: .
  options:
    description: 'Additional options'
    required: false
    default: '--reporter=vfile-reporter-pretty'
runs:
  using: 'docker'
  image: docker://pipelinecomponents/awesome-lint
  args:
    - awesome-lint
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
